version : '3'
services :


  db:
    image : "mysql:5.6"
    restart : always
    environment :
      MYSQL_DATABASE: DB1
      MYSQL_ROOT_PASSWORD: qwerty
    expose:
      - "3306"
    
  7th_container :
  
  #カレントディレクトリ中にあるDockerfileを参照してビルドする
    build : ./fake_twitter_site
    ports :                 # 公開ポート
      - "8030:8030"             # 外部公開ポート番号：コンテナのポート番号（存在していないと接続できない）
      # bashを打っておけばとりあえず動かしたままにできる
      # 再現性を意識して実行するcommandを記述すること
    command : bash -c "sleep 5 && pip install -r fake_twitter_site/requirements.txt && python fake_twitter_site/manage.py makemigrations && python fake_twitter_site/manage.py migrate && python fake_twitter_site/manage.py runserver 0.0.0.0:8030"
    #command : bash -c "pip install -r fake_twitter_site/requirements.txt && python fake_twitter_site/manage.py migrate && python fake_twitter_site/manage.py createsuperuser && python fake_twitter_site/manage.py runserver 0.0.0.0:8030"
    #command : bash
    volumes : 
      - ".:/usr/src/app"
    environment :
      7TH_CONTAINER_DB_PASSWORD :  aaaaa 
    depends_on :
      - db
    links:
      - db:db
    tty: true